version: '3.5'
services:
  restaurant.mobile:
    build:
      context: .
      dockerfile: ./docker/production.Dockerfile
    command: sh /usr/app/docker/entrypoint.production.sh
    user: node
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
