version: '3.5'

services:
  database__mongodb:
    image: mongo:latest
    environment:
      - MONGODB_USER="root" 
      - MONGODB_PASS="default"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./__database__:/data/db
