version: '3.3'
volumes:
  data:
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_USER="root" 
      - MONGODB_PASS="default"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./__database__:/data/db
    ports:
        - 27017:27017
