version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/production.Dockerfile
    command: sh /usr/app/docker/entrypoint.production.sh
    user: node
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true